server:
  port: 8080
  servlet:
    session:
      timeout: 30m
    encoding:
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 500
  error:
    path: /error


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB
  thymeleaf:
    cache: true
    devtools:
      restart:
        enabled: true
        additional-paths:
          - src/main/java
  jpa:
    hibernate:
      ddl-auto: update
    # DB configuration
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/finderapp?serverTimezone=Asia/Shanghai
    username: seldon
    password: sEd6SLBEnyLbrJWD

