server:
  port: 8080

spring:
  thymeleaf:
    cache: true
    devtools:
      restart:
        enabled: true
        additional-paths:
          - src/main/java
  jpa:
    hibernate:
      ddl-auto: update
    # DB configuration
  datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/finderapp?serverTimezone=Asia/Shanghai
      username: seldon
      password: sEd6SLBEnyLbrJWD
