server:
  port: 8080

spring:
  thymeleaf:
    cache: true
    devtools:
      restart:
        enabled: true
        additional-paths:
          - src/main/java
  jpa:
    hibernate:
      ddl-auto: update
    # DB configuration
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:47.111.7.158}:3306/finderapp?serverTimezone=Asia/Shanghai
    username: seldon
    password: sEd6SLBEnyLbrJWD

  mvc:
    static-path-pattern: /user_pic/**

  resources:
    static-locations: file:./file_upload